openvnmrj-utils tested and working (#6)
* Removed CLAs; use https://cla-assistant.io instead through webhook in GitHub

* added submitcontribution with testing script testrsync.sh

* fixed bugs in submitcontribution; checked testrsync.sh

* License typechange

* Require Apache LICENSE

* submitcontribution, old

* submitcontribution, newer

* Updated README

Changed ownership to UO.
Cleanup some markdown

* Use / at end of src

* Removed training /, added more to submitcontribution

* tag is based on the submission name combined with tag version (tags must be unique to each submission); bug fixes, -n removed from help

* minor fix; squash

* fixed LICENSE check

* ovjsubmit runs a shell to submit

* ovjsubmit runs a shell to submit, fixed missing +

* ovjsubmit runs a shell to submit, removed write to file

* Updated the ovjapps mechanism

Renamed ovjlist to ovjapps. Added a manual page. The user only needs
to run ovjapps. The listrepo script is called as needed.

* Added ovjsubmit macro to submit appdirs

This macro uses a popup to get the path of the appdir, a title, and
description. It calls the submitcontribution script to do all the
work. Added verbose option to submitcontribution

* Incorporated changes from Dan Iverson

* ovjsubmit from Dan Iverson

* added Apache license to maclib contributions

* renamed: ovjlist -> ovjapps to match Dan Iverson

* Set ovjapps to Dan Iverson's PR version

* Adds openvnmj appdir to user appdir
 (TODO: appmode Spectroscopy is default)

* listrepo adds openvnmrj-utils as appdir

* LICENSE has extra quotes that weren't parsed

* listrepo tracks remote branch

* Use the deprecated git branch --set-upstream because git 1.7.1 on CentOS doesn't know the new ways

* removed merge conflict

* changed update message to reflect origin maybe something different

* Fixed error in updating repositories

* Don't delete the openvnmrj appdir, we are using it...

* Add entry for GitHub user

* added tag, fixed submission

* fixed tag, fixed layout

* fixed layout; set title, don't set github name

* fixed title

* fixed title

* added -a to commit to update all changes, removed verbose in submit

* removed extra files from bin

* added a blank appdir as a starting point

* Try to make script less verbose

diff --git a/openvnmrj-utils/bin/listrepo b/openvnmrj-utils/bin/listrepo
--- a/openvnmrj-utils/bin/listrepo
+++ b/openvnmrj-utils/bin/listrepo
@@ -18,10 +18,9 @@
 # limitations under the License.
 #
 # This uses ONE repository (appdirs) in the GitHub OpenVnmrJ organization
-# It'll pull down or update thi repisitory.
+# It'll pull down or update the appdirs repository.
+
 # Each directory will hold one appdir, which then could be enabled or disabled
-# The script will update the file ~vnmrsys/TODO and append the appdir so
-# the GUI only needs to activate
 
 set -o nounset
 #set -e
@@ -46,7 +45,7 @@ OPTIONS
     -h
       show help and exit
     -v
-      output list of appliation directories
+      output list of application directories
 
 
 GITHUB USERNAME
@@ -210,7 +209,8 @@ if [[ -d "${repodir}"/.git ]]; then
   fi
 # repo exists already, just update
   cd "${repodir}" || { echo "cd ${repodir} failed. Aborting"; exit 1; }
-  echo "Updating repository from ${repo_url}"
+  echo "Updating repository from origin"
+  git remote -v
   git show-ref --verify --quiet refs/heads/"${localbranch}"
   if [[ $? == 0 ]]; then
     git pull origin ${localbranch} || { git pull origin master; }
@@ -245,6 +245,8 @@ else # make directory if necessary and clone
   git fetch --tags
   if [[ ! -z ${localbranch} ]]; then
     git checkout -b ${localbranch} || { echo "error in making new branch ${localbranch}"; exit 1; }
+    #git branch --set-upstream-to=origin/${localbranch} ${localbranch} || { echo "error in tracking  branch ${localbranch}"; exit 1; }
+    git branch --set-upstream ${localbranch} origin/${localbranch}  || { echo "error in tracking  branch ${localbranch}"; exit 1; }
   fi
 fi
 # at this point we have a repo in "${repodir}" and on the correct branch
@@ -254,12 +256,19 @@ appdirs=$(find . -maxdepth 1 -type d -exec basename {} \; | grep -v "^\.")
 
 # Let's add the openvnmrj-utils appdir to the Application Directories
 appdirfile="${vnmruser}/persistence/appdir_${USER}"
-utildir="${ovjhome}/appdirs/openvnmrj-utils"
+appmode="Spectroscopy"
+if [[ ! -f "${appdirfile}" ]]; then
+  cp "${vnmrsystem}/adm/users/userProfiles/appdir${appmode}.txt" "${appdirfile}"
+fi
+utildir="${ovjhome}/${repo}/openvnmrj-utils"
 appdiradded=$(grep openvnmrj-utils "${appdirfile}")
 if [[ -z ${appdiradded} && -d "${utildir}" ]]; then
     title=$(head -1 "${utildir}/title")
     echo "1;${ovjhome}/appdirs/openvnmrj-utils;${title}" >> "${appdirfile}"
 fi
+
+# copy license file (required for ovjsubmit)
+cp "${ovjhome}/${repo}/LICENSE" "${ovjhome}/"
 
 # Integration with Dan Iverson's UX
 extractdir=${ovjhome}/.extract
@@ -273,7 +282,7 @@ for dir in ${appdirs}; do
   else
     title=${dir}
   fi
-  echo -e "${title}"  >> "${extractdir}/list"
+  echo -e "${dir} ${title}"  >> "${extractdir}/list"
   if [[ -f "${dir}/description" ]]; then
     cat "${dir}/description" > "${extractdir}/${title}"
   else
@@ -288,13 +297,11 @@ for dir in ${appdirs}; do
     fi
   fi
 done
-# last entry is not shown in ovjlist; add \n at end for now
-echo -e "" >> "${extractdir}/list"
 
 if (( $verbose == 1 )); then
   echo -e "\n${underline}\n"
   cat <<-%
-The contributions of the repository are listed above with title and descripton.
+The contributions of the repository are listed above with title and description.
 
 To access any contribution, enable the contribution within OpenVnmrJ by 
 selecting "edit>Applications…"
